language: android
sudo: required
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+
    - '.+'

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug --stacktrace

install: true
